### ISSUE TITLE
react-rating is really big

### ISSUE THREAD

**Issue by Fandekasp** [dreyescat/react-rating#104]
When building my files with webpack, I can see that react-rating.js results in 23.85kb parsed and 6.75kb gzipped.
For comparison, React is 5.48kb parsed for 2.38kb gzipped.

This is very expensive for a single component. Can you explain why ?
And do you have any idea for optimizing this package ? or recommendations to a lighter alternative solution ?

Thank you for your support in advance

**Comment by dreyescat** [comment]
Hi @Fandekasp! Sorry for my late response.

It is a fair point! My main suspect would be `prop-types`. It was moved to a separate package in [v15.5](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html). As it is a *dependent* package now, it is bundled along with the rating component because it is not part of React anymore.

The only solution that comes to my mind right now is to get rid of `PropTypes`. At least in production.

**Comment by dreyescat** [comment]
I just manually removed all references to `PropTypes` from the code and generated the library and it halved the size. The `react-rating.min.js` size decreased from 23Kb to 11Kb.

**Comment by Fandekasp** [comment]
@dreyescat I see you use webpack, so you could have also used a plugin to do it for you: https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types :)
Thanks for the optimization, and if you find other tricks to reduce the size even more ... :heart:

**Comment by dreyescat** [comment]
It sounds good! Because I would like to keep them in dev. I mean, just strip `PropTypes` when the production build is generated.

If you feel comfortable adding this plugin yourself I am very happy accepting pull requests.

**Comment by Fandekasp** [comment]
Might take a while, but whenever I'll add it into my project, I'll also create a PR for react-rating. Thanks for your support.

**Comment by Fandekasp** [comment]
@dreyescat can you bump the package to 1.3.1 ? the current npm package is still 23kb

**Comment by dreyescat** [comment]
Sorry! I didn't explain it well 😞.

I removed manually all the stuff related to `PropTypes` in my local repo just to confirm my suspicion that it was one of the causes of the size increase. I didn't mean that I wanted to get rid of `PropTypes`. I think it sitll could be useful in devel. That's why I thought the idea of adding a [plugin that removes prop types](https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types) was perfect.

I tried to add this plugin myself right now but it seems the devel dependencies are getting old 😅. This plugin probably requires a higher version of babel than the one this component is using at the moment.

Maybe it is time for an upgrade of the dev dependencies. Let me try to upgrade them or maybe switch to a [toolchain](https://reactjs.org/docs/create-a-new-react-app.html#more-flexible-toolchains).

**Comment by Fandekasp** [comment]
Babel 5 :O Yes, please do ^^'

I'm myself in the process of migrating babel to v7, and eventually I'd like to try running `yarn install --flat` to reduce the bundle size, but that'll require all used packages to be supported by the same version of requirements.
I have a "make a react-rating PR to auth-remove proptypes" task in my checklist, but not sure when I'll be able to attack this. Maybe within a month. Thanks for looking at it before if you find time :heart:

**Comment by dreyescat** [comment]
I updated Babel to version 7 and other dev dependencies to their most up-to-date version. Only with this update the `react-rating.min.js` size has been reduced to 12.7KB. It seems a good start 😃.

Released [1.3.1](https://github.com/dreyescat/react-rating/releases/tag/v1.3.1).
