### ISSUE TITLE
Feature Request: trigger onChange when clicking the same value

### ISSUE THREAD

**Issue by Vodzo** [dreyescat/react-rating#106]
It would be nice if the component called the onChange method even when clicking the same value again. I want to use it to reset the value.

This used to work in earlier versions: https://github.com/dreyescat/react-rating/issues/35 but it seems that something changed since then

**Comment by dreyescat** [comment]
It's a fair request. Let me think about it. If I cannot figure out an *easy* way to accomplish this functionality with the current API I will bring `onClick` back.

**Comment by Vodzo** [comment]
Thank you for a quick reaction. If you are open for suggestion, maybe you could introduce a boolean prop for example "allowSameValueSelect" and handle it inside condition of handleClick method of RatingAPI layer. That way you retain backwards compatibility for others who prefer current implementation.

**Comment by dreyescat** [comment]
I have been thinking about your suggestion... but I feel unconfortable with habing a callback `onChange` that behaves differently depending on a flag. I even see it confusing because of the name. It conveys *changing* but if you have this flag enabled then it is called even if no change is done.

Anyway. I have *reintroduced* the [`onClick` callback](https://github.com/dreyescat/react-rating#callbacks). With this new property you should be able to accomplish what you need. Same way as before #35.

Released in [1.4.0](https://github.com/dreyescat/react-rating/releases/tag/v1.4.0)

**Comment by Vodzo** [comment]
Cool, makes sense. This will work prefectly. I'll implement it when it gets published on npmjs.

Cheers

**Comment by dreyescat** [comment]
@Vodzo Sorry! I forgot to publish it. Done!
