### ISSUE TITLE
Need to support inline style to set color

### ISSUE THREAD

**Issue by J-F-Liu** [dreyescat/react-rating#13]
e.g. `<Rating readonly={true} initialRate={value} style={{color: 'orange'}} empty="glyphicon glyphicon-star-empty" full="glyphicon glyphicon-star" fractions={2} />`

**Comment by dreyescat** [comment]
Hi @J-F-Liu,

If I am not wrong what you are trying to do is to set the symbols colors, right? In your case you can use a regular CSS `class` with the desired color and add this `class` to the list of classes for the `full` and `empty` properties.

For example, if you want your rating symbols to be orange just create a new CSS `class` with the desired style, in your case `color`:

```css
.orange-star {
  color: orange;
}
```

Then you just need to add this new class to the appropriate properties. In this case I just added the class to both, the `full` and `empty` attributes:

```javascript
<Rating readonly={true} initialRate={2} empty="glyphicon glyphicon-star-empty orange-star" full="glyphicon glyphicon-star orange-star" fractions={2} />
```

Check this [jsfiddle](https://jsfiddle.net/dreyescat/xrd4k8u7/).

Hope it helps.

**Comment by J-F-Liu** [comment]
Yes, this can solve my problem. But specify `orange-star` class name in both `empty` and `full` is a bit repetitive. 

Indeed I think React should pass common props such as id, className, style to component's wrapper element automatically, release the burden of component writing.

**Comment by J-F-Liu** [comment]
According to React's document, current solution of Transferring Props is
```
function FancyCheckbox(props) {
  var { checked, ...other } = props;
  var fancyClass = checked ? 'FancyChecked' : 'FancyUnchecked';
  // `other` contains { onClick: console.log } but not the checked property
  return (
    <div {...other} className={fancyClass} />
  );
}
ReactDOM.render(
  <FancyCheckbox checked={true} onClick={console.log.bind(console)}>
    Hello world!
  </FancyCheckbox>,
  document.getElementById('example')
);
```

**Comment by dreyescat** [comment]
Suppose I could propagate the props... But to what component? The `Rating` component is not a wrapper but a container of `Symbols`. Should I propagate those props to every `Symbol`? Even the `id` property?

Maybe it looks repetitive because you are using the same *style* (well, color) for both, the full and the empty symbol. But, imagine you decide not to use the same color for the empty state. If you only had one `style` to specify the color, how would you do that? That is why we have `empty` and `full` as different properties. You can see these properties as the data that will be used to create the empty and full symbols. Actually, you are doing exactly this with `glyphicon-star` and `glyphicon-star-empty`, aren't you?

For example:

```css
.my-symbol-empty {
  color: orange;
}

.my-symbol-full {
  color: red;
  font-size: 1.2em;
}
```

```javascript
<Rating readonly={true} initialRate={2} empty="glyphicon glyphicon-star-empty my-symbol-empty" full="glyphicon glyphicon-star my-symbol-full" fractions={2} />
```

**Comment by J-F-Liu** [comment]
Only propagate props to the outer most element returned from render method.

```
    let {
    start,
    stop,
    step,
    empty,
    placeholder,
    full,
    fractions,
    scale,
    onChange,
    onClick,
    onRate,
    ...other
    } = this.props;
    return (
      <span onMouseLeave={!readonly && this.handleMouseLeave} {...other}>
        {symbolNodes}
      </span>
    );
```

**Comment by dreyescat** [comment]
:+1:  I see your point. I just released a new minor version with this props propagation.
