### ISSUE TITLE
‘calm’ mode

### ISSUE THREAD

**Issue by kachkaev** [dreyescat/react-rating#17]
It would be nice if the rating component could be used in some sort of a ‘calm’ mode, i.e. not change the number of stars, circles, etc. when a mouse moves over it. This mode would be something like the `readonly` mode, but with callbacks enabled.

**Comment by kachkaev** [comment]
Awesome! Looking forward for a release to try this!

**Comment by dreyescat** [comment]
Just released. I thought it was going to take me more time... I have added a new [`quiet`](https://github.com/dreyescat/react-rating#properties) property to avoid the mouse over _animation_ while keeping the rest of callbacks, `onRate` included.

Let me know if I misunderstood your request otherwise.

**Comment by kachkaev** [comment]
Great! This work just as I expected. Special thanks for adding this mode to the list of examples!
