### ISSUE TITLE
how to rate half star

### ISSUE THREAD

**Issue by haunguyen90** [dreyescat/react-rating#20]
Is this package support to rate half star ?

**Comment by haunguyen90** [comment]
@dreyescat, any info for that ?

**Comment by dreyescat** [comment]
Yes. The [`fractions`](https://github.com/dreyescat/react-rating#properties) property allows you to specify in how many parts a symbol is _divided_. So, if you want half stars you just need to divide the symbol in 2 fractions:

```javascript
<Rating fractions={2} />
```

I have a [fractional jsfiddle](https://jsfiddle.net/dreyescat/0pe6z9q2/) that you can check and play around.

**Comment by sreevarsh** [comment]
Hi, how to change the default symbol (circle) to star?. I installed the component and I can only see the circle rating image. Can I switch to star rating?

Thank you

**Comment by dreyescat** [comment]
Hi @sreevarsh!

The easier way is to use some icon package like [bootstrap ](http://getbootstrap.com/components/) or [fontawesome](http://fontawesome.io/icons/). Then you just need to use the provided classes in your rating:

```jsx
<Rating empty="glyphicon glyphicon-star-empty" full="glyphicon glyphicon-star" />
```

Check this [jsfiddle](https://jsfiddle.net/dreyescat/cre6jcbh/) and the [demo]( http://dreyescat.github.io/react-rating/) page.

PS: Usually when you have a new question/problem/suggestion you should open a new issue instead of a comment in an unrelated issue. I mean, your question is totally unrelated to this issue at all :wink:.

**Comment by haunguyen90** [comment]
@dreyescat thank you very much. It's wonderful

**Comment by sreevarsh** [comment]
@dreyescat <https://github.com/dreyescat>  Sure, thank you very much. :)
