### ISSUE TITLE
When readonly=true, any way to remove cursor:pointer from wrapping span?

### ISSUE THREAD

**Issue by hchor** [dreyescat/react-rating#3]

**Comment by dreyescat** [comment]
Thanks for the feedback!

Yes. You are right. It makes more sense to show the `pointer` cursor only when you can interact with the component. Otherwise the `auto` pointer seems more appropriate.

It should have been solved in [v0.0.16](https://github.com/dreyescat/react-rating/releases/tag/v0.0.16).
