### ISSUE TITLE
How to use 'placeholder'

### ISSUE THREAD

**Issue by pentool** [dreyescat/react-rating#30]
Could you please provide an example on how to use the 'placeholder' prop? Regardless how I'm trying to use it, it has no effect. Eg

`placeholder={width: "32px", height: "32px"}`
or
`placeholder={<div className="red"></div>}`
or
`placeholder="<div></div>"`

It doesn't matter how I slice it, whatever I place into 'placeholder' is not showing up when I inspect the elements in the browser. An example would be helpful.

Thanks!

**Comment by dreyescat** [comment]
This property was added in pull request #6. The initial idea was to mimic the Netflix three state rating. In issue #19 you can find more info while I was trying to help someone to use it. There you can find an example (see [jsfiddle](https://jsfiddle.net/dreyescat/5nsbcvcw/)).

Hope it helps. Otherwise let me know and will try my best to help you out :wink:.

PS: I am thinking how to create a better documentation, probably based on examples with code. Definitely the weak point of this repo is documentation :blush:.

**Comment by pentool** [comment]
Hey thanks! Whoa, I completely misunderstood the purpose of "placeholder". No wonder it didn't work. I thought it was some sort of "wrapper" around the rating stars like `<div>...stars go here...</div>`. Apparently I was waaay off, LOL. But I get it now. Thanks for the help!
