### ISSUE TITLE
How to change default icon

### ISSUE THREAD

**Issue by anandrikka** [dreyescat/react-rating#39]
Unable to find proper documentation for changing the default icon, can any one help out ?

**Comment by dreyescat** [comment]
In order to customize icons you need `empty` and `full` properties. The former configures which icon/s to use when the rating is not selected while the latter configures the icon/s when the rating is selected (hover). These properties are so flexible that allows you to create really custom ratings.  Both properties accept  a `react element, inline style object, or classes`. Even `an array of such symbols that will be applied in a circular manner (round-robin)`.

A couple of examples:

1. Using [bootstrap glyphicons](https://jsfiddle.net/dreyescat/cre6jcbh/) classes:

    ```javascript
    <Rating empty="glyphicon glyphicon-star-empty big-star" full="glyphicon glyphicon-star big-star" />
    ```

2. Using [react elements](https://jsfiddle.net/dreyescat/06su57sw/):

   ```javascript
    <Rating start={0} stop={4} empty={[1,2,3,4].map(n => <span className="icon-text">{n}</span>)} full={[1,2,3,4].map(n => <span className="icon-text icon-selected">{n}</span>)} />
    ```

There are more examples in the [demo](http://dreyescat.github.io/react-rating/) page.


My apologies for the lack of proper documentation... It is something pending and a repeating concern several issues. There is even an open issue requesting to improve docs. I know how important is a good documentation but I have been lazy addressing this issue so far 😅.

**Comment by anandrikka** [comment]
Thanks @dreyescat , Present documentation looks fine, only suggestion is need some code examples on each prop

My usage of your rating component

`<Rating empty="fa fa-star-o" full="fa fa-star" fractions={2} stop={10} initialRate={movie.vote_average}/>`

How to add half stars and custom styles ?

**Comment by dreyescat** [comment]
You are on the right path. To have half stars you just need to set `fractions` property to `2`. You can customize the stars as you would do to any fontawesome icon with CSS. You can create new CSS classes and just assign them to the `empty` and/or `full` properties.

In [this example](https://jsfiddle.net/dreyescat/81qj5y3h/) I increased the size and changed the color of the symbols:

```css
.custom {
  font-size: 2em;
}
.custom-empty {
  color: blue;
}
.custom-full {
  color: red;
}
```

```javascript
<Rating empty="fa fa-star-o custom custom-empty" full="fa fa-star custom custom-full" fractions={2} stop={10} initialRate={3.5}/>
```

**Comment by djkwagala** [comment]
Please mark this as closed

**Comment by djkwagala** [comment]
@anandrikka please close this issue I believe @dreyescat answered sufficiently. otherwise I can help

**Comment by dreyescat** [comment]
I am going to close it. Feel free to reopen if needed.

**Comment by craigcosmo** [comment]
not working in 2019

**Comment by gulam092** [comment]
[SPFx.docx](https://github.com/dreyescat/react-rating/files/10024786/SPFx.docx)
