### ISSUE TITLE
Invalid prop `onClick` of type `boolean` supplied to `RatingSymbol`, expected `function`

### ISSUE THREAD

**Issue by jdonzet** [dreyescat/react-rating#66]
I have just migrated to 1.0.1 and this error is printed in console regarding internal props:

```
Warning: Failed prop type: Invalid prop `onClick` of type `boolean` supplied to `RatingSymbol`, expected `function`.
    in RatingSymbol (created by Rating)
    in Rating (created by RatingAPILayer)
    in RatingAPILayer (created by Rated)
   ...
```

This is also printed:
```
Warning: Failed prop type: Invalid prop `onMouseMove` of type `boolean` supplied to `RatingSymbol`, expected `function`.
    in RatingSymbol (created by Rating)
    in Rating (created by RatingAPILayer)
    in RatingAPILayer (created by Rated)
...
```

**Comment by mkarajohn** [comment]
@jdonzet this must have been fixed in https://github.com/dreyescat/react-rating/pull/67

Please upgrade and let us know if you still face issues :)

**Comment by dptoot** [comment]
@mkarajohn Has this been published to NPM?  We are still only seeing v1.0.1

**Comment by mkarajohn** [comment]
Yes, it has been published since last night :)

On Jan 3, 2018 8:30 PM, "James Lewis" <notifications@github.com> wrote:

@mkarajohn <https://github.com/mkarajohn> Has this been published to NPM?
We are still only seeing v1.0.1

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/dreyescat/react-rating/issues/66#issuecomment-355088853>,
or mute the thread

**Comment by jdonzet** [comment]
@mkarajohn Updated to 1.0.2 and the issue was fixed!
Thank you for the quick support.

**Comment by dptoot** [comment]
@mkarajohn Issue was all on our side.  Local npm repo caching fail!  Thanks!
